### ISSUE TITLE
Cherry-pick fixes for netty-native-demo maven project

### ISSUE THREAD

**Issue by olpaw** [cstancu/netty-native-demo#1]
@cstancu please cherry-pick https://github.com/cstancu/netty-native-demo/commit/04850b955a7ed5d79c9ae9f1df53e7d7621d2a07
onto your master. It contains fixes for your netty-native-demo maven project that should also be useful for the workflow you are describing.
- Most important, in [line 20](https://github.com/cstancu/netty-native-demo/commit/04850b955a7ed5d79c9ae9f1df53e7d7621d2a07#diff-600376dffeb79835ede4a0b285078036R20) I have added `<scope>provided</scope>` for the svm.jar dependency. This ensures that it is on the classpath only for building your project (with javac) but does not get **transitively** packed into the netty-svm-httpserver-full.jar.
- The official maven groupId for the `svm.jar` is `com.oracle.substratevm`. By using the official name you avoid conflicts if we finally have substratevm in maven central.
- By moving netty_reflection_config.json to src/main/resources/netty_reflection_config.json maven will automatically know this is a resource and package it into the jar file. This allows you to use `-H:ReflectionConfigurationResources` instead of `-H:ReflectionConfigurationFiles` which has the advantage of not being depended on where the resource file really is.

**Comment by cstancu** [comment]
Done. Thank you!
